# Introduction

In [ ]:
#import pytorch
import torch

### Tensor Example

Tensor is basically a multi-dimensional array. Pytorch supports running operations in GPU (Nvidia)

In [ ]:
x = torch.Tensor([1,2])
y = torch.Tensor([2,4])

print(x*y)

tensor([2., 8.])


### Zeros Example

2 * 5 array initialized with zeros

In [ ]:
z = torch.zeros([3,6])
print(z)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


### To get the array shape

Prints the dimension of the array

In [ ]:
z.shape

torch.Size([3, 6])

### Random Initialization of the array

Initialize array(Tensor) with random numbers

In [ ]:
a = torch.rand([3,6])
print(a)

tensor([[0.5471, 0.2800, 0.9700, 0.1266, 0.2974, 0.9210],
        [0.2196, 0.9911, 0.9365, 0.5811, 0.2127, 0.2177],
        [0.2956, 0.9812, 0.4596, 0.9118, 0.2254, 0.8442]])


### Reshaping a tensor

We can flatten a 3*6 Tensor by passing [1,18] to view function 

Sometimes we might have to perform flatten operation on pixels.For this, we can use the view function

In [ ]:
a = a.view([1,18])
print(a)

tensor([[0.5471, 0.2800, 0.9700, 0.1266, 0.2974, 0.9210, 0.2196, 0.9911, 0.9365,
         0.5811, 0.2127, 0.2177, 0.2956, 0.9812, 0.4596, 0.9118, 0.2254, 0.8442]])
